source 'https://github.com/tuya/tuya-pod-specs.git'
source "https://github.com/TuyaInc/TuyaPublicSpecs.git"
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'
inhibit_all_warnings!

target 'TuyaSmartOutdoorKit-Example-iOS-Objc' do
  pod 'TuyaSmartHomeKit'
  pod 'SVProgressHUD'
  pod 'MJRefresh'
  pod 'SDWebImage'
  #Dp multilingual
  pod 'TuyaSmartLangsExtraBizBundle'
  #outdoor
  pod 'TuyaSmartOutdoorKit', :path => '../../TuyaSmartOutdoorKit'

end
